---
title: "Amino acids"
output: 
  html_notebook:
    codes: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(tibble)

# pink/blue/
grp <- c("ET_B", "ET_P")
grp.col <- c("#FF6000", "#0080C0")

stg <- c("Before", "After")
stg.col <- c("#6288BA", "#C25D97")
```

### load data
```{r}
phen <- read.csv("../datset/phenotype/phenotype.grp.csv") %>% 
  mutate(Stage=factor(Stage, levels=stg),
         Group=factor(Group, levels=grp))
amf <- read.table("../datset/profile/Amino.profile")
gsf <- read.table("../datset/profile/Genus.profile")
spf <- read.table("../datset/profile/Species.profile")
```

### Figure4A 
```{r}
PCoAFun <- function(cfg) {
  pheAA <- inner_join(phen,
      amf %>% t() %>% data.frame() %>%
      rownames_to_column("SampleID"),
                    by = "SampleID")
  pheAA.before <- pheAA %>% filter(Stage==cfg)
  pheAA.prf <- pheAA.before[, -c(1:12)]
  pheAA.grp <- pheAA.before[, c(1:12), F]
  rownames(pheAA.prf) <- pheAA.grp$SampleID
  pheAA.grp$col <- with(pheAA.grp, ifelse(Group=="ET_B",
                          grp.col[1], grp.col[2]))
  library(vegan)  
  dist.e <- dist(pheAA.prf, method = "euclidean")
  model1 <- hclust(dist.e, method='ward.D2')
  result <- cutree(model1, k=2) %>% data.frame() %>% 
    rownames_to_column("SampleID") %>% 
    setNames(c("SampleID", "Ungroup"))
  grp.result <- inner_join(pheAA.grp, result) %>% 
    mutate(Ungroup=ifelse(Ungroup==1, "Cluster1", "Cluster2"),
           Shape=ifelse(Ungroup=="Cluster1", 21, 24))
  
  print(adonis(dist.e~Group, data = grp.result,
               permutations = 999)$aov.tab$`Pr(>F)`[1])
  print(adonis(dist.e~Ungroup, data = grp.result,
         permutations = 999)$aov.tab$`Pr(>F)`[1])

  mds <- cmdscale(dist.e, k=2, eig=T)
  plot(mds$points, col = grp.result$col, lwd = 2, 
       pch = 19,xlab = "MDS1", ylab = "MDS2")
  legend("bottomleft",inset = c(0.01, 0.01),
         grp, fill = grp.col, box.lty = 0, cex = .8)
}

#pdf("../pdf/Figure4A.pdf", width = 4, height = 4)
PCoAFun("Before")
#dev.off()
```

## comparsion between two enterotypes before intervention
```{r}
prefun <- function(y){
  sid <- intersect(as.character(phen$SampleID), colnames(y))
  phe <- phen %>% filter(SampleID%in%sid) %>%
    filter(Stage=="Before")
  prf <-  y %>% select(as.character(phe$SampleID)) %>%
    t() %>% data.frame() %>%
    rownames_to_column("SampleID")
  mdat <- inner_join(phe, prf, by = "SampleID")
  
  fr <- levels(phen$Group)
  wilcoxFun <- function(n, cfg){
    dat <- n %>% filter(Group%in%cfg)
    idx <- c("SampleID", "ID", "Group")
    datphe <- dat %>% select(idx)
    datprf <- dat %>% select(c(13:43))
    res <- apply(datprf, 2, function(x, grp){
      dat <- as.numeric(x)
      p <- wilcox.test(dat ~ grp)$p.value
      md <- median(dat)
      mdn <- tapply(dat, grp, median)
      if ( mdn[1] > mdn[2]) {
          enrich <- levels(grp)[1]
      } else {
          enrich <- levels(grp)[2]
      }
      occ <- tapply(dat, grp, function(x){
        round(sum(x > 0)/length(x), 4)})
      res <- c(p,enrich,occ,md,mdn)
      return(res)
     }, datphe$Group) %>%
      t(.) %>% data.frame(.) %>%
      rownames_to_column("Type") %>%
      varhandle::unfactor(.)
      
    colnames(res)[2:8] <- c("Pvalue", "Enrichment",
        paste0(fr, "_occurence"), "median", 
        paste0(fr, "_median"))
    if(length(cfg)==2){
      res$Block <- "Both"      
    }else{
      res$Block <- cfg
    }
    res$Num <- nrow(datphe)/2
    res.cln <- res %>% select(c(1, 9:10, 2:8)) %>%
       mutate(Pvalue=as.numeric(Pvalue),
             median=as.numeric(median),
             Zscore=ifelse(Enrichment=="ET_B",
              -qnorm(1-(Pvalue/2)), qnorm(1-(Pvalue/2)))) %>%
      arrange(Pvalue, median) %>%
      mutate(FDR = p.adjust(Pvalue, method = "BH"))
    return(res.cln)
  }

  res <- wilcoxFun(mdat, grp)
  return(res)
}

prePlot <- function(x){
  aa.grp <- prefun(x)
  idx <- c("Type", "Enrichment", "Pvalue", "Zscore")
  dat <- aa.grp %>% select(idx) %>% arrange(Enrichment, Zscore, Type)
  dat.cln <- dat
  dat.cln$Type <- factor(dat.cln$Type, levels = as.character(dat$Type))
  
  pl <- ggplot(dat.cln, aes(y=Type, x=Zscore, color=Enrichment))+ 
    geom_segment(xend=0, aes(yend=Type), size=3)+
    geom_vline(xintercept = 0)+
    geom_vline(xintercept = c(-1.96, 1.96),
               linetype="dashed", color="grey50")+
    theme_bw()+
    scale_color_manual(values = grp.col)+
    labs(x="Z score",
         y="")+
    scale_x_continuous(breaks=seq(-2.5, 2.5, 0.5),
                       limits=c(-2.5, 2.5))+
    theme(panel.grid.major = element_blank(),
          panel.grid.minor.x = element_blank(),
          legend.position = "NA",
          strip.text.y = element_blank(),
          axis.title = element_text(size=9, color="black", face="bold"),
          strip.text = element_text(size=10, color="black", face="bold"),
          axis.text = element_text(size=8, color="black"))
  return(pl)
}
```

### Figure4B
```{r}
prePlot(amf)
#ggsave("../pdf/Figure4B.pdf", width = 6, height = 4, dpi = 600)
```

```{r}
testfun <- function(y){
  wilfun <- function(y, tag){
    sid <- intersect(as.character(phen$SampleID), colnames(y))
    phe <- phen %>% filter(SampleID%in%sid) %>%
      filter(Stage==tag)
    prf <-  y %>% select(as.character(phe$SampleID)) %>%
      t() %>% data.frame() %>%
      rownames_to_column("SampleID")
    mdat <- inner_join(phe, prf, by = "SampleID")
    
    fr <- levels(phen$Group)
    wilcoxFun <- function(n, cfg){
      dat <- n %>% filter(Group%in%cfg)
      idx <- c("SampleID", "ID", "Group")
      datphe <- dat %>% select(idx)
      datprf <- dat %>% select(c(13:43))
      res <- apply(datprf, 2, function(x, grp){
        dat <- as.numeric(x)
        p <- wilcox.test(dat ~ grp)$p.value
        md <- mean(dat)
        mdn <- round(tapply(dat, grp, mean), 3)
        sd <- round(tapply(dat, grp, sd), 3)
        if ( mdn[1] > mdn[2]) {
            enrich <- levels(grp)[1]
        } else {
            enrich <- levels(grp)[2]
        }
        occ <- tapply(dat, grp, function(x){
          round(sum(x > 0)/length(x), 4)})
        msd <- c(paste0(mdn[1], "+/-", sd[1]), 
                 paste0(mdn[2], "+/-", sd[2]))
        res <- c(p,enrich,occ,md,msd)
        return(res)
       }, datphe$Group) %>%
        t(.) %>% data.frame(.) %>%
        rownames_to_column("Type") %>%
        varhandle::unfactor(.)
        
      colnames(res)[2:8] <- c("Pvalue", "Enrichment",
          paste0(fr, "_occurence"), "mean", 
          paste0(fr, "_mean"))
      res$Block <- tag
      res$Num <- nrow(datphe)/2
      res.cln <- res %>% select(c(1, 9:10, 2:8)) %>%
         mutate(Pvalue=as.numeric(Pvalue),
               mean=as.numeric(mean),
               Zscore=ifelse(Enrichment=="ET_B",
                -qnorm(1-(Pvalue/2)), qnorm(1-(Pvalue/2)))) %>%
        arrange(Pvalue, mean) %>%
        mutate(FDR = p.adjust(Pvalue, method = "BH"))
      return(res.cln)
    }
  
    res <- wilcoxFun(mdat, grp)
    return(res)
  }
  res1 <- wilfun(y, "Before")
  res2 <- wilfun(y, "After")
  res <- rbind(res1, res2)
  return(res)
}

ba.aa.t <- testfun(amf)
#write.csv(ba.aa.t, "../datset/compare/aa.stage.wilcox.csv", row.names = F)
```
### Figure 4C
```{r}
PCAFun <- function(y){
  idx <- c("Stage", "ID", "Group")
  sid <- intersect(colnames(y), as.character(phen$SampleID))
  phe <- phen %>% select(SampleID, idx) %>%
    filter(SampleID%in%sid) %>%
    arrange(SampleID, Stage) %>%
    mutate(Stage=factor(Stage, levels = stg),
                 Group=factor(Group, levels = grp))
  prf <- y[, colnames(y)%in%sid] %>%
    t() %>% data.frame()
  # pca 
  pca <- prcomp(scale(prf))
  library(factoextra)
  eig <- get_eig(pca)
  # explains variable 
  explains <- paste0(paste0("PC", seq(2)), "(", paste0(round(eig[1:2, 2], 2), "%"), ")")
  # principal component score of each sample
  score <- inner_join(pca$x %>% data.frame() %>% select(c(1:2)) %>% 
                        rownames_to_column("SampleID"), 
                      phe, by = "SampleID")
  # arrow  dataframe
  ArrowFun <- function(data, cfg1, cfg2){
    idx <- c("ID", "PC1", "PC2")
    dat1 <- subset(data, (Stage==cfg1), select = idx)
    dat2 <- subset(data, (Stage==cfg2), select = idx)
    colnames(dat2)[2:3] <- c("xend", "yend")
    res <- merge(dat1, dat2, by="ID")
  }
  bas.low <- ArrowFun(score, "Before", "After")
  
  pl <- ggplot(score, aes(x=PC1, y=PC2))+
        geom_point(aes(color=Stage), alpha=.8, size=3.5, shape=16)+
        geom_segment(data=bas.low,
                     aes(x=PC1, y=PC2, xend=xend, yend=yend),
                     arrow=arrow(length=unit(0.12,"cm"), ends="last", type = "closed"),
                     size=.3,
                     color= "black",
                     alpha=.5)+
        stat_ellipse(aes(group = Stage), linetype = 2)+
        stat_ellipse(aes(fill = Stage), geom = "polygon", alpha=0.2)+  
        labs(x=explains[1], y=explains[2])+
        scale_color_manual(values = stg.col,
                           labels = stg)+
        scale_fill_manual(values = stg.col,
                       labels = stg)+
        scale_x_continuous(breaks = seq(-8, 8, 2))+
        scale_y_continuous(breaks = seq(-6, 4, 2))+    
        guides(color=guide_legend(title = NULL,keywidth=.7,keyheight=.7),
               fill=guide_legend(title = NULL,keywidth=.7,keyheight=.7))+
        theme_bw()+        
        theme(axis.title = element_text(size=10, color="black", face="bold"),
                      axis.text = element_text(size=9, color="black"),
                      text = element_text(size=8, color="black"),
                      strip.text = element_text(size=9, color="black", face="bold"), 
                      panel.grid = element_blank(),
                      legend.text=element_text(size=10, color = "black"),
                      legend.position = c(1, 0),
                      legend.justification = c(1, 0),
                      legend.background = element_rect(color = "black", fill="white"))
  return(pl)
}

PCAFun(amf)
#ggsave("../pdf/Figure4C.pdf", width = 6, height = 4, dpi = 300)
```

### Figure 4D 
```{r}
postfun <- function(y, x=phen){
  sid <- intersect(as.character(x$SampleID), colnames(y))
  phe <- x %>% filter(SampleID%in%sid)
  prf <-  y %>% select(as.character(phe$SampleID)) %>%
    t() %>% data.frame() %>%
    rownames_to_column("SampleID")
  mdat <- inner_join(phe, prf, by = "SampleID")
  
  fr <- levels(x$Stage)
  wilcoxFun <- function(n, cfg){
    dat <- n %>% filter(Group%in%cfg)
    idx <- c("SampleID", "ID", "Stage")
    datphe <- dat %>% select(idx)
    datprf <- dat %>% select(c(13:43))
    res <- apply(datprf, 2, function(x, grp){
      dat <- as.numeric(x)
      p <- wilcox.test(dat ~ grp, paired = T)$p.value
      md <- median(dat)
      mdn <- tapply(dat, grp, median)
      if ( mdn[1] > mdn[2]) {
          enrich <- levels(grp)[1]
      } else {
          enrich <- levels(grp)[2]
      }
      occ <- tapply(dat, grp, function(x){
        round(sum(x > 0)/length(x), 4)})
      res <- c(p,enrich,occ,md,mdn)
      return(res)
     }, datphe$Stage) %>%
      t(.) %>% data.frame(.) %>%
      rownames_to_column("Type") %>%
      varhandle::unfactor(.)
      
    colnames(res)[2:8] <- c("Pvalue", "Enrichment",
        paste0(fr, "_occurence"), "median", 
        paste0(fr, "_median"))
    if(length(cfg)==2){
      res$Block <- "Both"      
    }else{
      res$Block <- cfg
    }
    res$Num <- nrow(datphe)/2
    res.cln <- res %>% select(c(1, 9:10, 2:8)) %>%
       mutate(Pvalue=as.numeric(Pvalue),
             median=as.numeric(median),
             Zscore=ifelse(Enrichment=="Before",
              -qnorm(1-(Pvalue/2)), qnorm(1-(Pvalue/2)))) %>%
      arrange(Pvalue, median) %>%
      mutate(FDR = p.adjust(Pvalue, method = "BH"))
    return(res.cln)
  }

  all <- wilcoxFun(mdat, grp) 
  b <- wilcoxFun(mdat, grp[1]) 
  p <- wilcoxFun(mdat, grp[2])  
  res <- rbind(all, b, p)
  return(res)
}

postPlot <- function(x){
  aa.stg <- postfun(x)
  idx <- c("Type", "Block", "Before_After_P", "Before_After_Z")
  dat.all <- aa.stg %>% filter(Block=="Both") %>% 
    select(Type, Block, FDR, Zscore) %>%
    setNames(idx)
  b <- aa.stg %>% filter(Block%in%grp[1]) %>% 
    select(Type, Block, FDR, Zscore) %>%
    setNames(idx)
  p <- aa.stg %>% filter(Block%in%grp[2]) %>% 
    select(Type, Block, FDR, Zscore) %>%
    setNames(idx)
  
  dat <- dat.all %>% filter(Before_After_P < 1) %>%
    mutate(dir=ifelse(Before_After_Z < 0, "decrease", "increase")) 
  dat.p.cln <- p %>% filter(Type%in%as.character(dat$Type)) %>%
    mutate(dir=ifelse(Before_After_Z < 0, "decrease", "increase"))
  dat.b.cln <- b %>% filter(Type%in%as.character(dat$Type)) %>%
    mutate(dir=ifelse(Before_After_Z < 0, "decrease", "increase"))
  dat.grp <- dat %>% select(c("Type", "dir",  grep("Z", colnames(dat)))) %>%
           setNames(c("Amino", "dir", "All")) %>%
           tidyr::gather(Group, Zscore, -c("Amino", "dir"))
  dat.p <- dat.p.cln %>% select(c("Type", "dir",  
                grep("Z", colnames(dat.p.cln)))) %>%
           setNames(c("Amino", "dir", "ETP")) %>%
           tidyr::gather(Group, Zscore, -c("Amino", "dir"))
  dat.b <- dat.b.cln %>% select(c("Type", "dir",  grep("Z", colnames(dat.b.cln)))) %>%
           setNames(c("Amino", "dir", "ETB")) %>%
           tidyr::gather(Group, Zscore, -c("Amino", "dir"))
  
  mdat <- rbind(dat.grp, dat.p, dat.b)
  ord_aa <- dat.grp %>% arrange(Zscore, dir) 
  mdat$Amino <- factor(mdat$Amino, levels = ord_aa$Amino)
  mdat$Group <- factor(mdat$Group, 
      levels = c("ETB", "ETP", "All"),
      labels = paste(c("ETB", "ETP", "All"), "Before vs After"))
  
  pl <- ggplot(mdat, aes(y=Amino, x=Zscore, color=dir))+ 
    geom_segment(xend=0, aes(yend=Amino), size=2)+
    geom_vline(xintercept = 0)+
    geom_vline(xintercept = c(-1.96, 1.96), linetype="dashed", color="grey50")+
    facet_wrap(facets = "Group", ncol = 3)+
    theme_bw()+
    scale_color_manual(values = stg.col)+
    labs(x="Z score",
         y="")+
    scale_x_continuous(breaks=seq(-6, 6, 2),
                       limits=c(-6.1, 6.1))+
    theme(panel.grid.major = element_blank(),
          panel.grid.minor.x = element_blank(),
          legend.position = "NA",
          strip.text.y = element_blank(),
          axis.title = element_text(size=9, color="black", face="bold"),
          strip.text = element_text(size=10, color="black", face="bold"),
          axis.text = element_text(size=8, color="black"))
  return(pl)
}

postPlot(amf)
#ggsave("../pdf/Figure4D.pdf", width = 6, height = 4, dpi = 600)
```

### Permanova

* delta amino acids and taxonomy
```{r}
library(vegan) 

perFun_delta_aa <- function(y) {
  
  # y <- spf
  
  sid <- intersect(phen$SampleID, intersect(colnames(amf), colnames(y))) 
  phe <- phen %>% filter(SampleID%in%sid) %>% 
    select(ID, Stage, SampleID) %>% 
    arrange(ID, Stage)
  
  phe_amf <- inner_join(phe, amf %>% t() %>% data.frame() %>% rownames_to_column("SampleID"),
                        by = "SampleID")
  amf_delta <- (phe_amf %>% filter(Stage==stg[1]) %>% select(-c("ID", "Stage", "SampleID")) -
               phe_amf %>% filter(Stage==stg[2]) %>% select(-c("ID", "Stage", "SampleID")) ) %>%
    mutate(ID = unique(as.character(phe_amf$ID))) %>%
    column_to_rownames("ID")
  
  phe_prf <- inner_join(phe, y %>% t() %>% data.frame() %>% rownames_to_column("SampleID"),
                        by = "SampleID")
  prf_delta <- (phe_prf %>% filter(Stage==stg[1]) %>% select(-c("ID", "Stage", "SampleID")) -
               phe_prf %>% filter(Stage==stg[2]) %>% select(-c("ID", "Stage", "SampleID")) ) %>%
    mutate(ID = unique(as.character(phe_prf$ID))) %>%
    column_to_rownames("ID")
  
  per <- apply(amf_delta, 2, function(x, pf){
  
    # x <- amf_delta$Arginine
    # pf <- prf_delta
    dat <- data.frame(value = x, pf) %>% na.omit()
    if (is.factor(dat$value)){
      datphe <- dat$value  
    }else{
      datphe <- dat$value
    }
    
    if (length(datphe) == 0 | unique(datphe) == 1) {
        res <- data.frame(length(datphe), rep(NA, 6))
        next
    }
      
    if (length(unique(datphe)) < 6) {
        datphe <- as.factor(datphe)
    } 
      
    # distance 
    datprf <- dat[, -1, F] 
    dis <- vegdist(datprf, method = "manhattan")
      
    set.seed(123)
    ad <- adonis(dis ~ datphe, permutations = 1000)
    tmp <- as.data.frame(ad$aov.tab) %>% slice(1)
    res <- c(length(datphe), as.numeric(tmp[, c(1:6)]))

    return(res)
    
    }, prf_delta) %>% t() %>% data.frame()
    
  colnames(per) <- c("SumsOfSample", "Df", "SumsOfSqs", 
                       "MeanSqs", "F.Model", "R2", "Pr(>F)")
  
  per$FDR <- p.adjust(per$`Pr(>F)`, method = "BH")
  
  return(per)
}

# Species and amino acids
spf.amf.delta.per <- perFun_delta_aa(spf)
write.csv(spf.amf.delta.per, "../datset/correlation/spf.amf.delta.csv")
```

* baseline taxonomy & change in amino acids
```{r}
perFun_aa <- function(y) {
  
  sid <- intersect(phen$SampleID, intersect(colnames(amf), colnames(y))) 
  phe <- phen %>% filter(SampleID%in%sid) %>% 
    select(ID, Stage, SampleID) %>% 
    arrange(ID, Stage)
  
  phe_amf <- inner_join(phe, amf %>% t() %>% data.frame() %>% rownames_to_column("SampleID"),
                        by = "SampleID")
  amf_delta <- (phe_amf %>% filter(Stage==stg[1]) %>% select(-c("ID", "Stage", "SampleID")) -
               phe_amf %>% filter(Stage==stg[2]) %>% select(-c("ID", "Stage", "SampleID")) ) %>%
    mutate(ID = unique(as.character(phe_amf$ID))) %>%
    column_to_rownames("ID")
  
  phe_prf <- inner_join(phe, y %>% t() %>% data.frame() %>% rownames_to_column("SampleID"),
                        by = "SampleID") %>% 
    filter(Stage==stg[1]) %>% 
    select(-c("ID", "Stage", "SampleID"))
  
  per <- apply(amf_delta, 2, function(x, pf){
  
    # x <- amf_delta$Arginine
    # pf <- prf_delta
    dat <- data.frame(value = x, pf) %>% na.omit()
    if (is.factor(dat$value)){
      datphe <- dat$value  
    }else{
      datphe <- dat$value
    }
    
    if (length(datphe) == 0 | unique(datphe) == 1) {
        res <- data.frame(length(datphe), rep(NA, 6))
        next
    }
      
    if (length(unique(datphe)) < 6) {
        datphe <- as.factor(datphe)
    } 
      
    # distance 
    datprf <- dat[, -1, F] 
    dis <- vegdist(datprf, method = "bray")
      
    set.seed(123)
    ad <- adonis(dis ~ datphe, permutations = 1000)
    tmp <- as.data.frame(ad$aov.tab) %>% slice(1)
    res <- c(length(datphe), as.numeric(tmp[, c(1:6)]))

    return(res)
    
    }, phe_prf) %>% t() %>% data.frame()
    
  colnames(per) <- c("SumsOfSample", "Df", "SumsOfSqs", 
                       "MeanSqs", "F.Model", "R2", "Pr(>F)")
  
  per$FDR <- p.adjust(per$`Pr(>F)`, method = "BH")
  
  return(per)
}

# baseline Species and amino acids
base.spf.amf.per <- perFun_aa(spf)
#write.csv(base.spf.amf.per, "../datset/correlation/base.spf.amf.delta.csv")
```
